-- NTT Lua/Luau Obfuscator Reference Skill
-- Documentation/example file. Safe to require/load: examples are wrapped in `if false then`.

--[[
Skill: Identifier Renaming

Goal

Rename local/parameter/upvalue mà không phá dynamic references.

SOURCE
]]

-- Example block (not executed)
if false then
    local mob = getmob(name)
    
    local function attackTarget(target)
        return attack(target)
    end
    
    return attackTarget(mob)
end

--[[
TARGET SHAPE
]]

-- Example block (not executed)
if false then
    local kQ7 = getmob(J2)
    
    local function f9x(P3)
        return qN(P3)
    end
    
    return f9x(kQ7)
end

--[[
Must distinguish

- locals
- parameters
- upvalues
- globals
- Roblox APIs
- reflective names generated by strings

Dangerous SOURCE
]]

-- Example block (not executed)
if false then
    loadstring("name1=" .. #items)()
    for i = 1, name1 do
        ...
    end
end

--[[
Nếu rename `name1` thành `Qx9` thì generated assignment string cũng phải đổi đúng context.

BAD SHAPE

Rename mọi spelling `name1` trong cả file hoặc protect toàn bộ spelling khỏi rename.

Cả hai đều dễ gây leak hoặc bug.

Safety Gate

Không rename khi chưa biết identifier đó có được dùng qua:

- `loadstring`
- `getfenv`
- `_ENV`
- `_G`
- generated source strings
]]
